use super::handlers;

#[repr(C)]
pub struct HardwareIdt([HardwareIdtEntry; 256]);

#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct HardwareIdtEntry {
    pointer_low: u16,
    gdt_selector: u16,
    options: EntryOptions,
    pointer_middle: u16,
    pointer_high: u32,
    reserved: u32
}

#[repr(transparent)]
#[derive(Debug, Clone, Copy)]
pub struct EntryOptions(u16);

impl HardwareIdt {
    pub fn new() -> Self {
        // for i in `seq 0 255`; do echo "HardwareIdtEntry::new(handle_irq_${i}),"; done
        let mut result = HardwareIdt([
            HardwareIdtEntry::new(handlers::handle_irq_0),
            HardwareIdtEntry::new(handlers::handle_irq_1),
            HardwareIdtEntry::new(handlers::handle_irq_2),
            HardwareIdtEntry::new(handlers::handle_irq_3),
            HardwareIdtEntry::new(handlers::handle_irq_4),
            HardwareIdtEntry::new(handlers::handle_irq_5),
            HardwareIdtEntry::new(handlers::handle_irq_6),
            HardwareIdtEntry::new(handlers::handle_irq_7),
            HardwareIdtEntry::new(handlers::handle_irq_8),
            HardwareIdtEntry::new(handlers::handle_irq_9),
            HardwareIdtEntry::new(handlers::handle_irq_10),
            HardwareIdtEntry::new(handlers::handle_irq_11),
            HardwareIdtEntry::new(handlers::handle_irq_12),
            HardwareIdtEntry::new(handlers::handle_irq_13),
            HardwareIdtEntry::new(handlers::handle_irq_14),
            HardwareIdtEntry::new(handlers::handle_irq_15),
            HardwareIdtEntry::new(handlers::handle_irq_16),
            HardwareIdtEntry::new(handlers::handle_irq_17),
            HardwareIdtEntry::new(handlers::handle_irq_18),
            HardwareIdtEntry::new(handlers::handle_irq_19),
            HardwareIdtEntry::new(handlers::handle_irq_20),
            HardwareIdtEntry::new(handlers::handle_irq_21),
            HardwareIdtEntry::new(handlers::handle_irq_22),
            HardwareIdtEntry::new(handlers::handle_irq_23),
            HardwareIdtEntry::new(handlers::handle_irq_24),
            HardwareIdtEntry::new(handlers::handle_irq_25),
            HardwareIdtEntry::new(handlers::handle_irq_26),
            HardwareIdtEntry::new(handlers::handle_irq_27),
            HardwareIdtEntry::new(handlers::handle_irq_28),
            HardwareIdtEntry::new(handlers::handle_irq_29),
            HardwareIdtEntry::new(handlers::handle_irq_30),
            HardwareIdtEntry::new(handlers::handle_irq_31),
            HardwareIdtEntry::new(handlers::handle_irq_32),
            HardwareIdtEntry::new(handlers::handle_irq_33),
            HardwareIdtEntry::new(handlers::handle_irq_34),
            HardwareIdtEntry::new(handlers::handle_irq_35),
            HardwareIdtEntry::new(handlers::handle_irq_36),
            HardwareIdtEntry::new(handlers::handle_irq_37),
            HardwareIdtEntry::new(handlers::handle_irq_38),
            HardwareIdtEntry::new(handlers::handle_irq_39),
            HardwareIdtEntry::new(handlers::handle_irq_40),
            HardwareIdtEntry::new(handlers::handle_irq_41),
            HardwareIdtEntry::new(handlers::handle_irq_42),
            HardwareIdtEntry::new(handlers::handle_irq_43),
            HardwareIdtEntry::new(handlers::handle_irq_44),
            HardwareIdtEntry::new(handlers::handle_irq_45),
            HardwareIdtEntry::new(handlers::handle_irq_46),
            HardwareIdtEntry::new(handlers::handle_irq_47),
            HardwareIdtEntry::new(handlers::handle_irq_48),
            HardwareIdtEntry::new(handlers::handle_irq_49),
            HardwareIdtEntry::new(handlers::handle_irq_50),
            HardwareIdtEntry::new(handlers::handle_irq_51),
            HardwareIdtEntry::new(handlers::handle_irq_52),
            HardwareIdtEntry::new(handlers::handle_irq_53),
            HardwareIdtEntry::new(handlers::handle_irq_54),
            HardwareIdtEntry::new(handlers::handle_irq_55),
            HardwareIdtEntry::new(handlers::handle_irq_56),
            HardwareIdtEntry::new(handlers::handle_irq_57),
            HardwareIdtEntry::new(handlers::handle_irq_58),
            HardwareIdtEntry::new(handlers::handle_irq_59),
            HardwareIdtEntry::new(handlers::handle_irq_60),
            HardwareIdtEntry::new(handlers::handle_irq_61),
            HardwareIdtEntry::new(handlers::handle_irq_62),
            HardwareIdtEntry::new(handlers::handle_irq_63),
            HardwareIdtEntry::new(handlers::handle_irq_64),
            HardwareIdtEntry::new(handlers::handle_irq_65),
            HardwareIdtEntry::new(handlers::handle_irq_66),
            HardwareIdtEntry::new(handlers::handle_irq_67),
            HardwareIdtEntry::new(handlers::handle_irq_68),
            HardwareIdtEntry::new(handlers::handle_irq_69),
            HardwareIdtEntry::new(handlers::handle_irq_70),
            HardwareIdtEntry::new(handlers::handle_irq_71),
            HardwareIdtEntry::new(handlers::handle_irq_72),
            HardwareIdtEntry::new(handlers::handle_irq_73),
            HardwareIdtEntry::new(handlers::handle_irq_74),
            HardwareIdtEntry::new(handlers::handle_irq_75),
            HardwareIdtEntry::new(handlers::handle_irq_76),
            HardwareIdtEntry::new(handlers::handle_irq_77),
            HardwareIdtEntry::new(handlers::handle_irq_78),
            HardwareIdtEntry::new(handlers::handle_irq_79),
            HardwareIdtEntry::new(handlers::handle_irq_80),
            HardwareIdtEntry::new(handlers::handle_irq_81),
            HardwareIdtEntry::new(handlers::handle_irq_82),
            HardwareIdtEntry::new(handlers::handle_irq_83),
            HardwareIdtEntry::new(handlers::handle_irq_84),
            HardwareIdtEntry::new(handlers::handle_irq_85),
            HardwareIdtEntry::new(handlers::handle_irq_86),
            HardwareIdtEntry::new(handlers::handle_irq_87),
            HardwareIdtEntry::new(handlers::handle_irq_88),
            HardwareIdtEntry::new(handlers::handle_irq_89),
            HardwareIdtEntry::new(handlers::handle_irq_90),
            HardwareIdtEntry::new(handlers::handle_irq_91),
            HardwareIdtEntry::new(handlers::handle_irq_92),
            HardwareIdtEntry::new(handlers::handle_irq_93),
            HardwareIdtEntry::new(handlers::handle_irq_94),
            HardwareIdtEntry::new(handlers::handle_irq_95),
            HardwareIdtEntry::new(handlers::handle_irq_96),
            HardwareIdtEntry::new(handlers::handle_irq_97),
            HardwareIdtEntry::new(handlers::handle_irq_98),
            HardwareIdtEntry::new(handlers::handle_irq_99),
            HardwareIdtEntry::new(handlers::handle_irq_100),
            HardwareIdtEntry::new(handlers::handle_irq_101),
            HardwareIdtEntry::new(handlers::handle_irq_102),
            HardwareIdtEntry::new(handlers::handle_irq_103),
            HardwareIdtEntry::new(handlers::handle_irq_104),
            HardwareIdtEntry::new(handlers::handle_irq_105),
            HardwareIdtEntry::new(handlers::handle_irq_106),
            HardwareIdtEntry::new(handlers::handle_irq_107),
            HardwareIdtEntry::new(handlers::handle_irq_108),
            HardwareIdtEntry::new(handlers::handle_irq_109),
            HardwareIdtEntry::new(handlers::handle_irq_110),
            HardwareIdtEntry::new(handlers::handle_irq_111),
            HardwareIdtEntry::new(handlers::handle_irq_112),
            HardwareIdtEntry::new(handlers::handle_irq_113),
            HardwareIdtEntry::new(handlers::handle_irq_114),
            HardwareIdtEntry::new(handlers::handle_irq_115),
            HardwareIdtEntry::new(handlers::handle_irq_116),
            HardwareIdtEntry::new(handlers::handle_irq_117),
            HardwareIdtEntry::new(handlers::handle_irq_118),
            HardwareIdtEntry::new(handlers::handle_irq_119),
            HardwareIdtEntry::new(handlers::handle_irq_120),
            HardwareIdtEntry::new(handlers::handle_irq_121),
            HardwareIdtEntry::new(handlers::handle_irq_122),
            HardwareIdtEntry::new(handlers::handle_irq_123),
            HardwareIdtEntry::new(handlers::handle_irq_124),
            HardwareIdtEntry::new(handlers::handle_irq_125),
            HardwareIdtEntry::new(handlers::handle_irq_126),
            HardwareIdtEntry::new(handlers::handle_irq_127),
            HardwareIdtEntry::new(handlers::handle_irq_128),
            HardwareIdtEntry::new(handlers::handle_irq_129),
            HardwareIdtEntry::new(handlers::handle_irq_130),
            HardwareIdtEntry::new(handlers::handle_irq_131),
            HardwareIdtEntry::new(handlers::handle_irq_132),
            HardwareIdtEntry::new(handlers::handle_irq_133),
            HardwareIdtEntry::new(handlers::handle_irq_134),
            HardwareIdtEntry::new(handlers::handle_irq_135),
            HardwareIdtEntry::new(handlers::handle_irq_136),
            HardwareIdtEntry::new(handlers::handle_irq_137),
            HardwareIdtEntry::new(handlers::handle_irq_138),
            HardwareIdtEntry::new(handlers::handle_irq_139),
            HardwareIdtEntry::new(handlers::handle_irq_140),
            HardwareIdtEntry::new(handlers::handle_irq_141),
            HardwareIdtEntry::new(handlers::handle_irq_142),
            HardwareIdtEntry::new(handlers::handle_irq_143),
            HardwareIdtEntry::new(handlers::handle_irq_144),
            HardwareIdtEntry::new(handlers::handle_irq_145),
            HardwareIdtEntry::new(handlers::handle_irq_146),
            HardwareIdtEntry::new(handlers::handle_irq_147),
            HardwareIdtEntry::new(handlers::handle_irq_148),
            HardwareIdtEntry::new(handlers::handle_irq_149),
            HardwareIdtEntry::new(handlers::handle_irq_150),
            HardwareIdtEntry::new(handlers::handle_irq_151),
            HardwareIdtEntry::new(handlers::handle_irq_152),
            HardwareIdtEntry::new(handlers::handle_irq_153),
            HardwareIdtEntry::new(handlers::handle_irq_154),
            HardwareIdtEntry::new(handlers::handle_irq_155),
            HardwareIdtEntry::new(handlers::handle_irq_156),
            HardwareIdtEntry::new(handlers::handle_irq_157),
            HardwareIdtEntry::new(handlers::handle_irq_158),
            HardwareIdtEntry::new(handlers::handle_irq_159),
            HardwareIdtEntry::new(handlers::handle_irq_160),
            HardwareIdtEntry::new(handlers::handle_irq_161),
            HardwareIdtEntry::new(handlers::handle_irq_162),
            HardwareIdtEntry::new(handlers::handle_irq_163),
            HardwareIdtEntry::new(handlers::handle_irq_164),
            HardwareIdtEntry::new(handlers::handle_irq_165),
            HardwareIdtEntry::new(handlers::handle_irq_166),
            HardwareIdtEntry::new(handlers::handle_irq_167),
            HardwareIdtEntry::new(handlers::handle_irq_168),
            HardwareIdtEntry::new(handlers::handle_irq_169),
            HardwareIdtEntry::new(handlers::handle_irq_170),
            HardwareIdtEntry::new(handlers::handle_irq_171),
            HardwareIdtEntry::new(handlers::handle_irq_172),
            HardwareIdtEntry::new(handlers::handle_irq_173),
            HardwareIdtEntry::new(handlers::handle_irq_174),
            HardwareIdtEntry::new(handlers::handle_irq_175),
            HardwareIdtEntry::new(handlers::handle_irq_176),
            HardwareIdtEntry::new(handlers::handle_irq_177),
            HardwareIdtEntry::new(handlers::handle_irq_178),
            HardwareIdtEntry::new(handlers::handle_irq_179),
            HardwareIdtEntry::new(handlers::handle_irq_180),
            HardwareIdtEntry::new(handlers::handle_irq_181),
            HardwareIdtEntry::new(handlers::handle_irq_182),
            HardwareIdtEntry::new(handlers::handle_irq_183),
            HardwareIdtEntry::new(handlers::handle_irq_184),
            HardwareIdtEntry::new(handlers::handle_irq_185),
            HardwareIdtEntry::new(handlers::handle_irq_186),
            HardwareIdtEntry::new(handlers::handle_irq_187),
            HardwareIdtEntry::new(handlers::handle_irq_188),
            HardwareIdtEntry::new(handlers::handle_irq_189),
            HardwareIdtEntry::new(handlers::handle_irq_190),
            HardwareIdtEntry::new(handlers::handle_irq_191),
            HardwareIdtEntry::new(handlers::handle_irq_192),
            HardwareIdtEntry::new(handlers::handle_irq_193),
            HardwareIdtEntry::new(handlers::handle_irq_194),
            HardwareIdtEntry::new(handlers::handle_irq_195),
            HardwareIdtEntry::new(handlers::handle_irq_196),
            HardwareIdtEntry::new(handlers::handle_irq_197),
            HardwareIdtEntry::new(handlers::handle_irq_198),
            HardwareIdtEntry::new(handlers::handle_irq_199),
            HardwareIdtEntry::new(handlers::handle_irq_200),
            HardwareIdtEntry::new(handlers::handle_irq_201),
            HardwareIdtEntry::new(handlers::handle_irq_202),
            HardwareIdtEntry::new(handlers::handle_irq_203),
            HardwareIdtEntry::new(handlers::handle_irq_204),
            HardwareIdtEntry::new(handlers::handle_irq_205),
            HardwareIdtEntry::new(handlers::handle_irq_206),
            HardwareIdtEntry::new(handlers::handle_irq_207),
            HardwareIdtEntry::new(handlers::handle_irq_208),
            HardwareIdtEntry::new(handlers::handle_irq_209),
            HardwareIdtEntry::new(handlers::handle_irq_210),
            HardwareIdtEntry::new(handlers::handle_irq_211),
            HardwareIdtEntry::new(handlers::handle_irq_212),
            HardwareIdtEntry::new(handlers::handle_irq_213),
            HardwareIdtEntry::new(handlers::handle_irq_214),
            HardwareIdtEntry::new(handlers::handle_irq_215),
            HardwareIdtEntry::new(handlers::handle_irq_216),
            HardwareIdtEntry::new(handlers::handle_irq_217),
            HardwareIdtEntry::new(handlers::handle_irq_218),
            HardwareIdtEntry::new(handlers::handle_irq_219),
            HardwareIdtEntry::new(handlers::handle_irq_220),
            HardwareIdtEntry::new(handlers::handle_irq_221),
            HardwareIdtEntry::new(handlers::handle_irq_222),
            HardwareIdtEntry::new(handlers::handle_irq_223),
            HardwareIdtEntry::new(handlers::handle_irq_224),
            HardwareIdtEntry::new(handlers::handle_irq_225),
            HardwareIdtEntry::new(handlers::handle_irq_226),
            HardwareIdtEntry::new(handlers::handle_irq_227),
            HardwareIdtEntry::new(handlers::handle_irq_228),
            HardwareIdtEntry::new(handlers::handle_irq_229),
            HardwareIdtEntry::new(handlers::handle_irq_230),
            HardwareIdtEntry::new(handlers::handle_irq_231),
            HardwareIdtEntry::new(handlers::handle_irq_232),
            HardwareIdtEntry::new(handlers::handle_irq_233),
            HardwareIdtEntry::new(handlers::handle_irq_234),
            HardwareIdtEntry::new(handlers::handle_irq_235),
            HardwareIdtEntry::new(handlers::handle_irq_236),
            HardwareIdtEntry::new(handlers::handle_irq_237),
            HardwareIdtEntry::new(handlers::handle_irq_238),
            HardwareIdtEntry::new(handlers::handle_irq_239),
            HardwareIdtEntry::new(handlers::handle_irq_240),
            HardwareIdtEntry::new(handlers::handle_irq_241),
            HardwareIdtEntry::new(handlers::handle_irq_242),
            HardwareIdtEntry::new(handlers::handle_irq_243),
            HardwareIdtEntry::new(handlers::handle_irq_244),
            HardwareIdtEntry::new(handlers::handle_irq_245),
            HardwareIdtEntry::new(handlers::handle_irq_246),
            HardwareIdtEntry::new(handlers::handle_irq_247),
            HardwareIdtEntry::new(handlers::handle_irq_248),
            HardwareIdtEntry::new(handlers::handle_irq_249),
            HardwareIdtEntry::new(handlers::handle_irq_250),
            HardwareIdtEntry::new(handlers::handle_irq_251),
            HardwareIdtEntry::new(handlers::handle_irq_252),
            HardwareIdtEntry::new(handlers::handle_irq_253),
            HardwareIdtEntry::new(handlers::handle_irq_254),
            HardwareIdtEntry::new(handlers::handle_irq_255)
        ]);
        result.0[8].options.0 |= (::gdt::DOUBLE_FAULT_IST_INDEX & 0x0F);
        result.0[0x80].options.0 |= 3 << 13;
        result
    }

    pub fn load(&'static self) {
        use core::mem::size_of;
        use x86_64::instructions::tables::{lidt, DescriptorTablePointer};

        let ptr = DescriptorTablePointer {
            base: self as *const _ as u64,
            limit: (size_of::<Self>() - 1) as u16,
        };

        unsafe { lidt(&ptr) };
    }
}

impl HardwareIdtEntry {
    fn new(handler: extern "C" fn() -> !) -> Self {
        let addr = handler as *const u8 as u64;
        HardwareIdtEntry {
            gdt_selector: x86_64::instructions::segmentation::cs().0,
            pointer_low: addr as u16,
            pointer_middle: (addr >> 16) as u16,
            pointer_high: (addr >> 32) as u32,
            options: EntryOptions::minimal(),
            reserved: 0
        }
    }
}

impl EntryOptions {
    /// Creates a minimal options field with all the must-be-one bits set.
    const fn minimal() -> Self {
        EntryOptions(0b1000_1110_0000_0000)
    }
}
